In [6]:
### Import numpy as np and print the version number.
import numpy as np
np.__version__

'1.16.5'

In [9]:
### Create a 1D array of numbers from 0 to 9
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
### Create a 3×3 numpy array of all True’s


In [12]:
### Convert a 1D array to a 2D array with 2 rows
a=np.arange(8)
b=a.reshape(2,4)
np.

AttributeError: 'numpy.ndarray' object has no attribute 'b'

In [13]:

### Extract all odd numbers from arr
arr=np.arange(1,10)
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

In [15]:
### Replace all odd numbers in arr with -1
arr[arr%2!=0]=-1
arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

### Import numpy as np and print the version number.

### Create a 1D array of numbers from 0 to 9

### Create a 3×3 numpy array of all True’s

### Extract all odd numbers from arr


### Replace all odd numbers in arr with -1

### Convert a 1D array to a 2D array with 2 rows

### Stack arrays a and b vertically

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

### Stack the arrays a and b horizontally.

### Get the positions where elements of a and b match

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

### Get all items between 5 and 10 from a.

Input:

a = np.array([2, 6, 1, 9, 10, 3, 27])

### Convert the function maxx that works on two scalars, to work on two arrays.

Input:

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5
Desired Output:

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

### swap columns 1 and 2 in the array arr.
arr = np.arange(9).reshape(3,3)
arr</pre

### How to reverse the rows of a 2D array?
arr = np.arange(9).reshape(3,3)
arr</pre

### Reverse the columns of a 2D array arr.
arr = np.arange(9).reshape(3,3)
arr
In [ ]:

### Write a NumPy program to generate five random numbers from the normal distribution

### Write a NumPy program to generate six random integers between 10 and 30

### Write a NumPy program to create a 3x3x3 array with random values

### Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

### Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable

### Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).


### Read an JPEG image into a numpy array, return the size and shap of that image